CC=gcc -Wall

all: pf

pf: pf.c

	$(CC) -v pf.c -o pf -lm

clean:
	@rm pf particle_it1.txt particle_it2.txt particle_it3.txt particle_it4.txt particle_it5.txt particle_it6.txt particle_it7.txt particle_it8.txt particle_it9.txt particle_it10.txt particle_it11.txt particle_it12.txt particle_it13.txt particle_it14.txt particle_it15.txt particle_it16.txt particle_it17.txt particle_it18.txt particle_it19.txt particle_it20.txt 

backup:
	@ mv pf blackup/
	@mv particle_it1.txt backup/
	@mv particle_it2.txt backup/
	@mv particle_it3.txt backup/
	@mv particle_it4.txt backup/
	@mv particle_it5.txt backup/
	@mv particle_it6.txt backup/
	@mv particle_it7.txt backup/
	@mv particle_it8.txt backup/
	@mv particle_it9.txt backup/
	@mv particle_it10.txt backup/
	@mv particle_it11.txt backup/
	@mv particle_it12.txt backup/
	@mv particle_it13.txt backup/
	@mv particle_it14.txt backup/
	@mv particle_it15.txt backup/
	@mv particle_it16.txt backup/
	@mv particle_it17.txt backup/
	@mv particle_it18.txt backup/
	@mv particle_it19.txt backup/
	@mv particle_it20.txt backup/

